-- PostgreSQL Production Database Schema for demo workspace
-- Domain Architecture: Clinical Diagnostics & LIS Telemetry (healthcare)
-- Generated by BizzMitra AI Engine
-- Problem Statement Reference:
-- "Project managers often set and track task deadlines without factoring in employee leave, so a deadline gets fixed without knowing whether the assigned person will actually be available for the full task duration. This gap means there's no built-in buffer or handover preparation when someone goes on leave mid-task — work simply stalls or gets rushed at the last minute because the leave was never factored into how the deadline was structured in the first place, rather than being planned around from the start. Build a simple web app called \"TaskFlow\" for a single project manager to manage projects, tasks, and team leave — where the app prevents assigning a task to someone who's on leave during the task's scheduled dates. Core Features (MVP only): Team Members — Add/edit/delete a team member (name only, keep it minimal). Leave Management — Add/edit/delete a leave record for a team member: select member, start date, end date. Show a simple list/calendar view of all upcoming and past leave records. Projects — Add/edit/delete a project: name, start date, end date. Tasks — Add/edit/delete a task under a project: title, assigned team member (dropdown), start date, due date, status (To Do / In Progress / Done). Leave-Aware Assignment Block — When assigning or editing a task's assignee + dates, check if the selected team member has any leave record overlapping the task's start–due date range. If so, block the assignment with a clear inline error (e.g., \"Priya is on leave from June 5–8, which overlaps this task's dates — choose another date range or team member.\"). Project View — A view per project showing all its tasks grouped by status (To Do / In Progress / Done), like a simple kanban board. Team Availability Overview — A simple dashboard showing each team member and their upcoming leave dates at a glance, so the PM can plan assignments before hitting the block."

CREATE TABLE IF NOT EXISTS public.healthcare_records (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  col1_data TEXT NOT NULL, -- Semantic Mapping: Test Investigation Panel
  col2_data TEXT NOT NULL, -- Semantic Mapping: Analyzer Instrument ID
  status TEXT NOT NULL,    -- Semantic Mapping: Laboratory Stage
  badge TEXT DEFAULT 'Active',
  assignee TEXT NOT NULL,  -- Semantic Mapping: Pathologist Lead
  metric_value TEXT NOT NULL, -- Semantic Mapping: Report TAT SLA
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.healthcare_records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read-write for demo application"
  ON public.healthcare_records
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- Team and Role Authentication table
CREATE TABLE IF NOT EXISTS public.healthcare_users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL,
  badge TEXT NOT NULL,
  department TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.healthcare_users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read-write for authenticated users"
  ON public.healthcare_users
  FOR ALL
  USING (true)
  WITH CHECK (true);
